---
# install apache on target servers
- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    ansible.builtin.yum:
      name: httpd

  - name: install support for php
    ansible.builtin.yum:
      name: php
