---
# install apache on target servers
- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    ansible.builtin.yum:
      name: httpd
    when: ansible_distribution == "RedHat"

  - name: install support for php
    ansible.builtin.yum:
      name: php
    when: ansible_distribution == "RedHat"
